services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${RUN_PORT}:8080"
    environment:
      RUN_ADDRESS: ${RUN_ADDRESS}
    develop:
      watch:
        - action: rebuild
          path: .
          files:
            - ./**/*.go
            - ./go.mod
            - ./go.sum